#!/usr/bin/env bash

# Auto-detect device: use serial port for Pi 3 + Teensy, or hidg0 for Pi Zero
if [ -e /dev/serial0 ]; then
  DEV=/dev/serial0
else
  DEV=/dev/hidg0
fi

echo "$@" | /home/pi/pizero-usb-hid-keyboard/hid-gadget-test "$DEV" keyboard
